-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/exit",
    [2] = "menu.mainmenu:session/restart",
    [3] = "workspacelayout:",
    [4] = "workspacename:dev",
    [5] = "workspacelayout:full",
    [6] = "workspacename:full",
    [7] = "framename:Main",
}

