-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart",
    [2] = "menu.mainmenu:session restart",
    [3] = "menu.mainmenu:session/exit",
    [4] = "workspacelayout:",
    [5] = "workspacename:dev",
    [6] = "man:",
    [7] = "workspacelayout:full",
    [8] = "workspacename:fullscreen",
    [9] = "framename:Main",
}

