-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "Main",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["tls"] = 1064,
                            ["tl"] = {
                                ["tls"] = 962,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Notion WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW",
                                                ["geom"] = {
                                                    ["y"] = 20,
                                                    ["x"] = 1,
                                                    ["w"] = 960,
                                                    ["h"] = 1043,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 8388642,
                                                        ["checkcode"] = 1,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 6,
                                                            ["x"] = 3,
                                                            ["w"] = 955,
                                                            ["h"] = 1031,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                            [2] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<3>",
                                                ["hidden"] = true,
                                                ["geom"] = {
                                                    ["y"] = 20,
                                                    ["x"] = 1,
                                                    ["w"] = 960,
                                                    ["h"] = 1043,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 25165955,
                                                        ["checkcode"] = 2,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["x"] = 0,
                                                            ["w"] = 960,
                                                            ["h"] = 1043,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                                ["brs"] = 958,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "Notion WFrame<1>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<2>",
                                                ["hidden"] = true,
                                                ["geom"] = {
                                                    ["y"] = 20,
                                                    ["x"] = 1,
                                                    ["w"] = 956,
                                                    ["h"] = 1043,
                                                },
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 29360162,
                                                        ["checkcode"] = 3,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 6,
                                                            ["x"] = 1,
                                                            ["w"] = 955,
                                                            ["h"] = 1031,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                            [2] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<6>",
                                                ["geom"] = {
                                                    ["y"] = 20,
                                                    ["x"] = 1,
                                                    ["w"] = 956,
                                                    ["h"] = 1043,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 39845959,
                                                        ["checkcode"] = 4,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 1,
                                                            ["x"] = 2,
                                                            ["w"] = 952,
                                                            ["h"] = 1041,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 16,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "fullscreen",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 1,
                                ["type"] = "WFrame",
                                ["name"] = "Notion WFrame<2>",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<1>",
                                        ["geom"] = {
                                            ["y"] = 20,
                                            ["x"] = 1,
                                            ["w"] = 1918,
                                            ["h"] = 1059,
                                        },
                                        ["switchto"] = true,
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 23068706,
                                                ["checkcode"] = 5,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 1,
                                                    ["x"] = 2,
                                                    ["w"] = 1915,
                                                    ["h"] = 1057,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                    [2] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<4>",
                                        ["hidden"] = true,
                                        ["geom"] = {
                                            ["y"] = 20,
                                            ["x"] = 1,
                                            ["w"] = 1918,
                                            ["h"] = 1059,
                                        },
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 27262979,
                                                ["checkcode"] = 6,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 0,
                                                    ["x"] = 0,
                                                    ["w"] = 1918,
                                                    ["h"] = 1059,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                    [3] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<5>",
                                        ["hidden"] = true,
                                        ["geom"] = {
                                            ["y"] = 20,
                                            ["x"] = 1,
                                            ["w"] = 1918,
                                            ["h"] = 1059,
                                        },
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 31457282,
                                                ["checkcode"] = 7,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 0,
                                                    ["x"] = 0,
                                                    ["w"] = 1918,
                                                    ["h"] = 1059,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["name"] = "dev",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                        },
                        ["split_tree"] = {
                            ["tls"] = 960,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<3>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "horizontal",
                            ["brs"] = 960,
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<4>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 300,
                            ["x"] = 640,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                },
                ["hidden"] = true,
            },
        },
    },
}

