-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/exit",
    [2] = "workspacelayout:full",
    [3] = "workspacename:fullscreen",
    [4] = "framename:Main",
}

