-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/exit",
    [2] = "workspacelayout:",
    [3] = "workspacename:fs",
    [4] = "menu.mainmenu:session/restart",
    [5] = "workspacename:",
    [6] = "workspacename:pippin",
}

