-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/exit",
    [2] = "framename:vm",
    [3] = "workspacelayout:full",
    [4] = "workspacename:",
}

